# Generated by Django 3.2.7 on 2024-01-17 18:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.IntegerField(unique=True)),
                ('color', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('height', models.DecimalField(decimal_places=1, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_items', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Ожидание оплаты'), (2, 'Оплачен'), (3, 'В пути'), (4, 'Товар в пункте назначения')])),
                ('items', models.ManyToManyField(to='product.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
