# Generated by Django 3.2.7 on 2024-02-12 12:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240121_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('КБТ', 'Крупнобытовая техника'), ('МБТ', 'Мелкобытовая техника'), ('ТВ', 'Телевизоры'), ('НМ', 'New Media'), ('Acc', 'Аксессуры')], max_length=17, null=True),
        ),
    ]
