# Generated by Django 3.2.7 on 2024-02-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
