# Generated by Django 3.2.7 on 2024-02-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_item_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидание оплаты'), (2, 'Оплачен'), (3, 'В пути'), (4, 'Товар в пункте назначения')], default=1),
        ),
    ]
