# Generated by Django 4.1.13 on 2024-02-26 13:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('КБТ', 'Крупнобытовая техника'), ('МБТ', 'Мелкобытовая техника'), ('ТВ', 'Телевизоры'), ('НМ', 'New Media'), ('Acc', 'Аксессуры')], default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Ожидание оплаты'), (3, 'Оплачен'), (4, 'В пути'), (5, 'Товар в пункте назначения')], default=1),
        ),
    ]
