# Generated by Django 3.2.7 on 2024-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('0', 'Ожидание транзакции')], max_length=255),
        ),
    ]
