# Generated by Django 4.1.13 on 2024-02-29 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
