# Generated by Django 5.0.1 on 2024-01-15 13:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.IntegerField(unique=True)),
                ('color', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('height', models.DecimalField(decimal_places=1, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_items', models.PositiveIntegerField()),
                ('status', models.BooleanField(choices=[(True, 'Выполнено'), (False, 'Ожидание транзакции')])),
                ('items', models.ManyToManyField(to='midas.item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='users/avatar')),
                ('born', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('favorites', models.ManyToManyField(to='midas.item')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[(True, 'Выполнено'), (False, 'Ожидание транзакции')], max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='midas.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midas.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midas.user'),
        ),
    ]
