# Generated by Django 5.0.1 on 2024-01-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0004_order_supplies_alter_item_id_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ManyToManyField(null=True, to='midas.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.item'),
        ),
    ]
